// Seed shown when VITE_API_BASE is unset (GitHub Pages). Generated by running app.core.build_matrix
// on a CXR pneumothorax triage DhfProject (IEC 62304 class B): one ml-samd-validator evidence
// record (AMBIGUOUS, needs review), one failed verification (VER-2), one draft requirement (SRS-4)
// and one unmitigated risk (RC-4). Bands, gaps and coverage are real build_matrix output.
import type { Matrix } from "./types";

export const seedMatrix: Matrix = {
  "project_id": "cxr-ptx-triage",
  "generated_at": "2026-09-15T10:00:00Z",
  "requirements": [
    {
      "id": "UN-1",
      "level": "user_need",
      "text": "Radiologists need studies with suspected pneumothorax surfaced at the top of the reading worklist within 60 s of acquisition.",
      "rationale": "Median time-to-read for critical findings drives the clinical benefit claim.",
      "parent_id": null,
      "iec_62304_class": "B",
      "acceptance_criteria": [],
      "status": "approved"
    },
    {
      "id": "REQ-1",
      "level": "system",
      "text": "The device shall flag a chest radiograph as suspected pneumothorax with sensitivity >= 0.90 and specificity >= 0.85 on the locked validation set.",
      "rationale": "",
      "parent_id": "UN-1",
      "iec_62304_class": "B",
      "acceptance_criteria": [
        "sensitivity >= 0.90 (95% CI lower bound >= 0.87)",
        "specificity >= 0.85"
      ],
      "status": "approved"
    },
    {
      "id": "REQ-2",
      "level": "system",
      "text": "The device shall present the triage flag as a worklist priority only and shall not render a diagnostic statement or annotate the image.",
      "rationale": "Keeps the device a CADt triage aid (21 CFR 892.2080).",
      "parent_id": "UN-1",
      "iec_62304_class": "B",
      "acceptance_criteria": [],
      "status": "approved"
    },
    {
      "id": "REQ-3",
      "level": "system",
      "text": "The device shall detect post-market performance drift beyond +/-0.02 on sensitivity or AUC against the locked baseline and escalate to human review before any redeployment.",
      "rationale": "PCCP performance boundary; drift evidence is produced by ml-samd-validator.",
      "parent_id": null,
      "iec_62304_class": "B",
      "acceptance_criteria": [
        "every metric beyond tolerance is reported with a confidence band",
        "no autonomous redeployment"
      ],
      "status": "approved"
    },
    {
      "id": "SRS-1",
      "level": "software",
      "text": "The inference service shall return a pneumothorax probability and a binary flag at threshold 0.35 within 30 s of receiving the DICOM study.",
      "rationale": "",
      "parent_id": "REQ-1",
      "iec_62304_class": "B",
      "acceptance_criteria": [],
      "status": "approved"
    },
    {
      "id": "SRS-2",
      "level": "software",
      "text": "The worklist adapter shall emit an HL7 ORU priority flag only; free-text findings fields shall be left empty.",
      "rationale": "",
      "parent_id": "REQ-2",
      "iec_62304_class": "B",
      "acceptance_criteria": [],
      "status": "approved"
    },
    {
      "id": "SRS-3",
      "level": "software",
      "text": "The drift monitor shall run a two-proportion z-test per metric against the locked baseline and route each result through HIGH / AMBIGUOUS / LOW bands.",
      "rationale": "",
      "parent_id": "REQ-3",
      "iec_62304_class": "B",
      "acceptance_criteria": [],
      "status": "approved"
    },
    {
      "id": "SRS-4",
      "level": "software",
      "text": "The inference service shall reject studies with missing pixel-spacing metadata and log the rejection.",
      "rationale": "Raised after VER-1 root-cause; awaiting design review approval.",
      "parent_id": "REQ-1",
      "iec_62304_class": "B",
      "acceptance_criteria": [],
      "status": "draft"
    }
  ],
  "design_outputs": [
    {
      "id": "DO-1",
      "title": "Inference service",
      "description": "ResNet-50 classifier behind a FastAPI endpoint.",
      "artifact_path": "src/inference/service.py",
      "requirement_ids": [
        "REQ-1",
        "SRS-1"
      ]
    },
    {
      "id": "DO-2",
      "title": "HL7 worklist adapter",
      "description": "Maps the flag to ORU-R01 OBR-5 priority.",
      "artifact_path": "src/integration/hl7_adapter.py",
      "requirement_ids": [
        "REQ-2",
        "SRS-2"
      ]
    },
    {
      "id": "DO-3",
      "title": "Drift monitor",
      "description": "Wraps ml-samd-validator; exports ValidationEvidence.",
      "artifact_path": "src/monitoring/drift.py",
      "requirement_ids": [
        "REQ-3",
        "SRS-3"
      ]
    },
    {
      "id": "DO-4",
      "title": "DICOM preflight check",
      "description": "Metadata gate ahead of inference.",
      "artifact_path": "src/inference/preflight.py",
      "requirement_ids": [
        "SRS-4"
      ]
    }
  ],
  "verifications": [
    {
      "id": "VER-1",
      "method": "test",
      "description": "Retrospective performance test on the locked 2,000-study validation set.",
      "requirement_ids": [
        "REQ-1",
        "SRS-1"
      ],
      "result": "pass",
      "executed_at": "2026-06-12T09:00:00Z",
      "evidence_ref": "reports/VER-1_performance.pdf"
    },
    {
      "id": "VER-2",
      "method": "test",
      "description": "HL7 integration test against three PACS vendors.",
      "requirement_ids": [
        "SRS-2"
      ],
      "result": "fail",
      "executed_at": "2026-07-03T09:00:00Z",
      "evidence_ref": "reports/VER-2_hl7.pdf"
    },
    {
      "id": "VER-3",
      "method": "test",
      "description": "Drift monitor unit and contract tests against ml-samd-validator schema.",
      "requirement_ids": [
        "REQ-3",
        "SRS-3"
      ],
      "result": "pass",
      "executed_at": "2026-07-20T09:00:00Z",
      "evidence_ref": "tests/test_drift.py"
    },
    {
      "id": "VER-4",
      "method": "inspection",
      "description": "UI and HL7 message inspection: no diagnostic text present.",
      "requirement_ids": [
        "REQ-2"
      ],
      "result": "pass",
      "executed_at": "2026-07-21T09:00:00Z",
      "evidence_ref": "reports/VER-4_inspection.pdf"
    },
    {
      "id": "VER-5",
      "method": "demonstration",
      "description": "Usability demonstration of worklist re-ordering with 6 radiologists.",
      "requirement_ids": [
        "UN-1"
      ],
      "result": "pass",
      "executed_at": "2026-08-02T09:00:00Z",
      "evidence_ref": "reports/VER-5_usability.pdf"
    }
  ],
  "validations": [
    {
      "id": "VAL-1",
      "source": "ml-samd-validator",
      "evidence_id": "5f1c2b3e-8a77-4d2c-9d0e-7b6a1c4e2f90",
      "requirement_ids": [
        "REQ-1",
        "REQ-3"
      ],
      "model_id": "cxr-pneumothorax",
      "overall_band": "AMBIGUOUS",
      "requires_human_review": true,
      "generated_at": "2026-09-01T08:15:00Z",
      "summary": "cxr-pneumothorax v1.2.0: drift AMBIGUOUS over 2 metric(s), requires human review, fairness flagged=False",
      "raw": {
        "schema_version": "1.0",
        "generated_at": "2026-09-01T08:15:00Z",
        "model_id": "cxr-pneumothorax",
        "version": "1.2.0",
        "baseline": {
          "model_id": "cxr-pneumothorax",
          "version": "1.2.0",
          "locked_metrics": {
            "sensitivity": 0.9,
            "specificity": 0.85,
            "auc": 0.93,
            "f1": 0.88,
            "calibration_slope": 1.0
          },
          "baseline_date": "2026-01-01",
          "dataset_hash": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          "risk_classification": "II",
          "sample_size": 1000
        },
        "snapshot": {
          "model_id": "cxr-pneumothorax",
          "timestamp": "2026-03-01T00:00:00Z",
          "metrics": {
            "sensitivity": 0.88,
            "auc": 0.95,
            "extra": 0.5
          },
          "subgroup_breakdown": [
            {
              "subgroup": "age>65",
              "metrics": {
                "auc": 0.9
              },
              "sample_size": 120
            }
          ],
          "sample_size": 500,
          "drift_from_baseline": {
            "sensitivity": -0.020000000000000018,
            "auc": 0.019999999999999907
          }
        },
        "drift": {
          "model_id": "cxr-pneumothorax",
          "snapshot_timestamp": "2026-03-01T00:00:00Z",
          "metrics": [
            {
              "metric": "sensitivity",
              "baseline_value": 0.9,
              "snapshot_value": 0.88,
              "delta": -0.020000000000000018,
              "p_value": 0.23684856028158163,
              "verdict": "drifted",
              "confidence": 0.7631514397184184,
              "band": "AMBIGUOUS",
              "reasoning": "sensitivity delta -0.0200, drifted, confidence 0.76 (AMBIGUOUS). Flag for human interpretation: verdict 'drifted' but sample sizes give only moderate power."
            },
            {
              "metric": "auc",
              "baseline_value": 0.93,
              "snapshot_value": 0.95,
              "delta": 0.019999999999999907,
              "p_value": 0.1338207800597215,
              "verdict": "stable",
              "confidence": 0.71,
              "band": "AMBIGUOUS",
              "reasoning": "auc delta +0.0200, stable, confidence 0.71 (AMBIGUOUS). Flag for human interpretation: sample sizes give only moderate power."
            }
          ],
          "overall_band": "AMBIGUOUS",
          "requires_human_review": true,
          "iec_62304_note": "IEC 62304 software safety class B assigned from FDA SaMD risk class II: class A = no injury possible, B = non-serious injury possible, C = death or serious injury possible. Classification is provisional pending hazard analysis by the manufacturer.",
          "iso_14971_note": "ISO 14971: observed performance deviations are treated as hazardous situations. The risk control is human review of every flagged deviation before any deployment decision; this report is evidence, not a release decision."
        },
        "fairness": {
          "model_id": "cxr-pneumothorax",
          "threshold": 0.05,
          "findings": [
            {
              "subgroup": "age>65",
              "metric": "auc",
              "baseline_value": 0.93,
              "subgroup_value": 0.9,
              "delta": -0.030000000000000027,
              "verdict": "stable",
              "flagged": false,
              "confidence": 0.7858780221625611,
              "band": "AMBIGUOUS",
              "reasoning": "[age>65, n=120] auc delta -0.0300, stable, confidence 0.79 (AMBIGUOUS). Flag for human interpretation: verdict 'stable' but sample sizes give only moderate power."
            }
          ],
          "any_flagged": false,
          "aggregate_passed": true,
          "note": "Subgroup flags may exist even when aggregate metrics pass; aggregate performance does not establish subgroup equity."
        },
        "pccp_status": {
          "model_id": "cxr-pneumothorax",
          "change_type": "retrain",
          "decision": "insufficient information",
          "rationale": "Description under 20 characters or no expected metric deltas supplied.",
          "violated_boundaries": [],
          "confidence_band": "LOW"
        },
        "model_card": {
          "model_id": "cxr-pneumothorax",
          "version": "1.2.0",
          "intended_use": "Worklist triage of suspected pneumothorax on adult chest radiographs",
          "training_data_summary": "42k adult CXR studies, 6 sites, 2019-2024",
          "performance_by_subgroup": [
            {
              "subgroup": "age>65",
              "metrics": {
                "auc": 0.9
              },
              "sample_size": 120
            }
          ],
          "known_limitations": [
            "pediatric"
          ],
          "pccp_reference": "PCCP-001",
          "gmlp_checklist": {
            "multidisciplinary_expertise": true,
            "good_software_engineering": true,
            "representative_data": true,
            "independent_test_sets": true,
            "reference_standard": true,
            "design_fit_for_use": true,
            "human_ai_team_focus": true,
            "clinically_relevant_testing": true,
            "clear_user_information": true,
            "deployed_model_monitoring": true
          },
          "iec_62304_safety_class": "B",
          "iso_14971_risk_controls": [
            "human review"
          ]
        },
        "iec_62304": {
          "safety_class": "B",
          "rationale": "IEC 62304 software safety class B assigned from FDA SaMD risk class II: class A = no injury possible, B = non-serious injury possible, C = death or serious injury possible. Classification is provisional pending hazard analysis by the manufacturer."
        },
        "iso_14971": {
          "hazards": [
            "sensitivity drift -0.0200 (AMBIGUOUS confidence)",
            "auc drift +0.0200 (AMBIGUOUS confidence)"
          ],
          "risk_controls": [
            "human review"
          ],
          "residual_risk_statement": "Residual risk is accepted only after a qualified reviewer disposes each flagged finding; this evidence package asserts no autonomous go/no-go decision (ISO 14971 clause 7/8)."
        },
        "evidence_id": "5f1c2b3e-8a77-4d2c-9d0e-7b6a1c4e2f90",
        "requirement_ids": [
          "REQ-1",
          "REQ-3"
        ]
      }
    }
  ],
  "risk_controls": [
    {
      "id": "RC-1",
      "hazard": "Missed pneumothorax (false negative)",
      "hazardous_situation": "Flagged-negative study is read late in the worklist",
      "harm": "Delayed treatment of tension pneumothorax",
      "severity": 5,
      "probability": 2,
      "control_measure": "Sensitivity floor of 0.90 plus radiologist reads every study regardless of flag",
      "requirement_ids": [
        "REQ-1"
      ],
      "verification_ids": [
        "VER-1"
      ],
      "residual_risk_acceptable": true,
      "risk_index": 10
    },
    {
      "id": "RC-2",
      "hazard": "Undetected post-market performance drift",
      "hazardous_situation": "Model degrades silently on a new scanner fleet",
      "harm": "Systematic missed findings",
      "severity": 4,
      "probability": 3,
      "control_measure": "Automated drift detection with mandatory human review of AMBIGUOUS/LOW findings",
      "requirement_ids": [
        "REQ-3"
      ],
      "verification_ids": [
        "VER-3"
      ],
      "residual_risk_acceptable": true,
      "risk_index": 12
    },
    {
      "id": "RC-3",
      "hazard": "Triage flag misread as a diagnosis",
      "hazardous_situation": "Clinician treats on the flag without the radiology read",
      "harm": "Unnecessary chest drain",
      "severity": 4,
      "probability": 2,
      "control_measure": "Flag-only presentation; no diagnostic text or image annotation",
      "requirement_ids": [
        "REQ-2"
      ],
      "verification_ids": [
        "VER-4"
      ],
      "residual_risk_acceptable": true,
      "risk_index": 8
    },
    {
      "id": "RC-4",
      "hazard": "Automation bias",
      "hazardous_situation": "Radiologist de-prioritises unflagged studies and misses a subtle pneumothorax",
      "harm": "Delayed treatment",
      "severity": 4,
      "probability": 3,
      "control_measure": "Labelling and training: flag absence is not a negative result",
      "requirement_ids": [],
      "verification_ids": [],
      "residual_risk_acceptable": null,
      "risk_index": 12
    }
  ],
  "links": [
    {
      "source_id": "DO-1",
      "target_id": "REQ-1",
      "kind": "implements",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "DO-1 lists REQ-1 in requirement_ids"
    },
    {
      "source_id": "DO-1",
      "target_id": "SRS-1",
      "kind": "implements",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "DO-1 lists SRS-1 in requirement_ids"
    },
    {
      "source_id": "DO-2",
      "target_id": "REQ-2",
      "kind": "implements",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "DO-2 lists REQ-2 in requirement_ids"
    },
    {
      "source_id": "DO-2",
      "target_id": "SRS-2",
      "kind": "implements",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "DO-2 lists SRS-2 in requirement_ids"
    },
    {
      "source_id": "DO-3",
      "target_id": "REQ-3",
      "kind": "implements",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "DO-3 lists REQ-3 in requirement_ids"
    },
    {
      "source_id": "DO-3",
      "target_id": "SRS-3",
      "kind": "implements",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "DO-3 lists SRS-3 in requirement_ids"
    },
    {
      "source_id": "DO-4",
      "target_id": "SRS-4",
      "kind": "implements",
      "confidence": 0.75,
      "band": "AMBIGUOUS",
      "reasoning": "DO-4 lists SRS-4 in requirement_ids; target SRS-4 is draft (-0.15)"
    },
    {
      "source_id": "VER-1",
      "target_id": "REQ-1",
      "kind": "verifies",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "test VER-1 passed (reports/VER-1_performance.pdf)"
    },
    {
      "source_id": "VER-1",
      "target_id": "SRS-1",
      "kind": "verifies",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "test VER-1 passed (reports/VER-1_performance.pdf)"
    },
    {
      "source_id": "VER-2",
      "target_id": "SRS-2",
      "kind": "verifies",
      "confidence": 0.2,
      "band": "LOW",
      "reasoning": "failed verification does not evidence coverage"
    },
    {
      "source_id": "VER-3",
      "target_id": "REQ-3",
      "kind": "verifies",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "test VER-3 passed (tests/test_drift.py)"
    },
    {
      "source_id": "VER-3",
      "target_id": "SRS-3",
      "kind": "verifies",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "test VER-3 passed (tests/test_drift.py)"
    },
    {
      "source_id": "VER-4",
      "target_id": "REQ-2",
      "kind": "verifies",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "inspection VER-4 passed (reports/VER-4_inspection.pdf)"
    },
    {
      "source_id": "VER-5",
      "target_id": "UN-1",
      "kind": "verifies",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "demonstration VER-5 passed (reports/VER-5_usability.pdf)"
    },
    {
      "source_id": "VAL-1",
      "target_id": "REQ-1",
      "kind": "validates",
      "confidence": 0.55,
      "band": "AMBIGUOUS",
      "reasoning": "ml-samd-validator evidence 5f1c2b3e-8a77-4d2c-9d0e-7b6a1c4e2f90 band AMBIGUOUS (-0.10: requires human review)"
    },
    {
      "source_id": "VAL-1",
      "target_id": "REQ-3",
      "kind": "validates",
      "confidence": 0.55,
      "band": "AMBIGUOUS",
      "reasoning": "ml-samd-validator evidence 5f1c2b3e-8a77-4d2c-9d0e-7b6a1c4e2f90 band AMBIGUOUS (-0.10: requires human review)"
    },
    {
      "source_id": "RC-1",
      "target_id": "REQ-1",
      "kind": "mitigates",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "Sensitivity floor of 0.90 plus radiologist reads every study regardless of flag implemented by REQ-1"
    },
    {
      "source_id": "RC-2",
      "target_id": "REQ-3",
      "kind": "mitigates",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "Automated drift detection with mandatory human review of AMBIGUOUS/LOW findings implemented by REQ-3"
    },
    {
      "source_id": "RC-3",
      "target_id": "REQ-2",
      "kind": "mitigates",
      "confidence": 0.9,
      "band": "HIGH",
      "reasoning": "Flag-only presentation; no diagnostic text or image annotation implemented by REQ-2"
    }
  ],
  "gaps": [
    {
      "item_id": "VAL-1",
      "kind": "unreviewed_validation",
      "severity": "medium",
      "band": "AMBIGUOUS",
      "reasoning": "cxr-pneumothorax v1.2.0: drift AMBIGUOUS over 2 metric(s), requires human review, fairness flagged=False; a qualified reviewer must disposition it"
    },
    {
      "item_id": "RC-4",
      "kind": "unmitigated_risk",
      "severity": "high",
      "band": "LOW",
      "reasoning": "Automation bias: control measure is not traced to any requirement"
    },
    {
      "item_id": "UN-1",
      "kind": "missing_design_output",
      "severity": "medium",
      "band": "HIGH",
      "reasoning": "no design output implements UN-1 (21 CFR 820.30(d))"
    },
    {
      "item_id": "UN-1",
      "kind": "missing_validation",
      "severity": "medium",
      "band": "HIGH",
      "reasoning": "no validation evidence covers UN-1 (21 CFR 820.30(g))"
    },
    {
      "item_id": "REQ-2",
      "kind": "missing_validation",
      "severity": "medium",
      "band": "HIGH",
      "reasoning": "no validation evidence covers REQ-2 (21 CFR 820.30(g))"
    },
    {
      "item_id": "SRS-1",
      "kind": "missing_validation",
      "severity": "low",
      "band": "HIGH",
      "reasoning": "no validation evidence covers SRS-1 (21 CFR 820.30(g))"
    },
    {
      "item_id": "SRS-2",
      "kind": "failed_verification",
      "severity": "high",
      "band": "HIGH",
      "reasoning": "VER-2 failed against SRS-2"
    },
    {
      "item_id": "SRS-2",
      "kind": "missing_validation",
      "severity": "low",
      "band": "HIGH",
      "reasoning": "no validation evidence covers SRS-2 (21 CFR 820.30(g))"
    },
    {
      "item_id": "SRS-3",
      "kind": "missing_validation",
      "severity": "low",
      "band": "HIGH",
      "reasoning": "no validation evidence covers SRS-3 (21 CFR 820.30(g))"
    }
  ],
  "coverage": {
    "design_output": 0.8571428571428571,
    "verification": 0.8571428571428571,
    "validation": 0.2857142857142857,
    "risk_control": 0.42857142857142855
  },
  "overall_band": "LOW",
  "iec_62304_note": "IEC 62304 software safety class B: §5.1.1 requires the software development plan to establish traceability between system requirements, software requirements, software system tests and risk control measures; §5.2 (software requirements analysis) and §5.7 (software system testing) must demonstrate it. Traceability is mandatory for class B/C; gaps below block release.",
  "iso_14971_note": "ISO 14971 §7: each hazard needs a risk control measure (§7.1) implemented as a requirement (§7.2) whose effectiveness is verified (§7.3). 4 risk control(s) recorded, 1 unmitigated. The residual-risk acceptability statement (§7.4, §8) is the manufacturer's; the Archivist reports the chain and does not assert acceptability."
};
